[feat]메인페이지 중 인기검색어 섹션 구현과  태블릿,모바일 반응형 디자인
yourteacher-org/yourteacher-fe pull request #30
Opened 2024-03-13 07:39 UTC by hongdayeong

적용

# Pull Request 요약

> PR에 대한 내용을 작성해주세요.
- SearchwordSection 컴포넌트를 구현합니다.
- SearchwordSection 컴포넌트의  태블릿, 모바일 반응형 디자인을 반영합니다. 
<br>

## 작업 내용

> 작업 내용에 대해서 작성해주세요.
- SearchwordSection 컴포넌트 구현
- SearchwordSection 컴포넌트의  태블릿 디자인 반영
- SearchwordSection 컴포넌트의 모바일 디자인을 반영

<br>

## 참고 사항

> 참고 사항이 있다면 첨부해주세요.
![image](https://github.com/yourteacher-org/yourteacher-fe/assets/127013736/58cecb4e-c69d-410c-a3a5-b3fc272145a0)
![image](https://github.com/yourteacher-org/yourteacher-fe/assets/127013736/b9173548-b04f-4c48-b256-0373744582da)

<br>

## 관련 이슈

> closing할 이슈 번호를 작성해주세요.

- Close #29 

<br>

2024-03-13 15:40 UTC, seongjin2427 requested changes
먹땡님, 코멘트 확인 부탁드려요~!!
수정하시면서 모르시는 부분 있으시면 물어봐주세요~!! 👍

2024-03-13 15:40 UTC, seongjin2427 commented on src/assets/img/ZoomClick.png
아이콘이 png 파일이네요!
png 파일로 사용하시면, 테두리가 흐려지거나 하는 등의 부작용이 있습니다!
svg 파일로 아이콘만 사용해주세요!

2024-03-13 15:40 UTC, seongjin2427 commented on src/layouts/MainLayout.tsx
> +      <SearchwordSection />
여기는 레이아웃만 잡는 곳이라서 여기서 `SearchwordSection` 컴포넌트를 렌더링 하시면 안됩니다!
`Home` 컴포넌트에서 렌더링 하는 방식으로 변경 부탁드려요!

2024-03-13 15:40 UTC, seongjin2427 commented on src/pages/Home/Home.tsx
>    return <div>메인 페이지</div>;
```ts
<div>
  <SearchwordSection />
</div>
```
으로 변경해서 렌더링하면 좋을 것 같습니다.
`return <div>메인 페이지 </div>` 밖에서 렌더링 하려고 하셔서,
안 보여가지구 `MainLayout` 에러 렌더링 하려고 하셨던 것 같네요!

2024-03-13 15:40 UTC, seongjin2427 commented on src/pages/Home/SearchwordSection.tsx
> +    return Array.from({ length: visibleItemCount }, (_, index) => {
여기서 보여지는 `인기 검색어` 및 `조회수: XXX`는 추후에 서버에서 받는 데이터를 기반으로 렌더링하게 될 겁니다.
현재의 구현방식에서는 나중에 수정을 조금 해야할지도 몰라요!

구현을 잘 해주셨는데 조금 복잡한 방식으로 구현하신 것 같아요!
단순히 Mock data로만 배열로 만드셨어도 괜찮았을 것 같습니다.

ex)
```typescript
const MOCK_DATA = [
    {
        id: 1,
        searchWord: '인기 검색어',
        views: 100
    },
    {
        id: 2,
        searchWord: '인기 검색어',
        views: 100
    },
    ...
];
```

2024-03-13 15:40 UTC, seongjin2427 commented on src/pages/Home/SearchwordSection.tsx
> +          className={`flex text-l ml-32 transition duration-300 ease-in-out pl-5 mt-5 mb-39 ${
구현해주신 UI가 피그마 상의 디자인과 좀 상이한 부분이 있습니다.
1. 인기 검색어의 전체 길이가 짧습니다.
2. 데스크탑, 태블릿 디자인만 구현

- 피그마 디자인 (데스크탑)
  <img width="1134" alt="image" src="https://github.com/yourteacher-org/yourteacher-fe/assets/59536977/cfcada16-6b2a-48f1-99b3-34e4f7df1c12">

<br />

- 구현모습 (데스크탑)
  <img width="1918" alt="image" src="https://github.com/yourteacher-org/yourteacher-fe/assets/59536977/ec87536b-d1bf-43da-bb1c-54a63e150589">

<br />

- 깨지는 모바일 반응형
  <img width="1014" alt="image" src="https://github.com/yourteacher-org/yourteacher-fe/assets/59536977/aab0ed26-a859-4bcb-a798-abca00df3f4a">

<br />

반응형과 관련되서는 아래 정리해서 공유드려 보아요!
- 데스크탑 : 1280px 이상일 때 보이는 모습 (`xl:`)
    - ex) `className="xl:w-10"`
- 태블릿: 1024px ~ 1279px 사이일 때 보이는 모습 (`lg:`)
    - ex) `className="lg:w-10"`
- 모바일: 1023px 이하일 때 보이는 모습(`sm:`)
    - ex) `className="sm:w-10"`

2024-03-14 06:26 UTC, hongdayeong commented on src/pages/Home/Home.tsx
>    return <div>메인 페이지</div>;
확인 후 수정하였습니다~

2024-03-14 06:27 UTC, hongdayeong commented on src/layouts/MainLayout.tsx
> +      <SearchwordSection />
확인 후 수정하였습니다~

2024-03-15 08:16 UTC, hongdayeong commented on src/assets/img/ZoomClick.png
변경하였습니다!!

2024-03-16 07:22 UTC, hongdayeong commented on src/pages/Home/SearchwordSection.tsx
> +    return Array.from({ length: visibleItemCount }, (_, index) => {
변경하였습니다!!

2024-03-16 07:23 UTC, hongdayeong commented
> 먹땡님, 코멘트 확인 부탁드려요~!! 수정하시면서 모르시는 부분 있으시면 물어봐주세요~!! 👍

2024-03-16 14:37 UTC, seongjin2427 commented
먹땡님!
앞전 커밋을 살펴봤을 때, 커밋하시는 단위가 너무 하나로 통으로 되어있으신것 같긴 합니다.
제가 코멘트 드린 것들 하나 단위로 끊어서 커밋해주시는 것도 좋을 것 같아요!! 하하 👍

2024-03-20 10:30 UTC, hongdayeong commented on src/pages/Home/SearchwordSection.tsx
> +          className={`flex text-l ml-32 transition duration-300 ease-in-out pl-5 mt-5 mb-39 ${
변경했습니다~

2024-03-20 13:17 UTC, seongjin2427 approved these changes
고생하셨습니다~!

2024-03-21 23:25 UTC, merged