[fix]zoom 아이콘 이미지 파일 svg로 변경
yourteacher-org/yourteacher-fe pull request #31
Opened 2024-03-20 11:12 UTC by hongdayeong

# Pull Request 요약

> PR에 대한 내용을 작성해주세요.
zoom 아이콘 이미지 파일 svg로 변경 
<br>

## 작업 내용

> 작업 내용에 대해서 작성해주세요.
zoom 아이콘 이미지 파일 png에서 svg로 변경 
<br>

## 참고 사항

> 참고 사항이 있다면 첨부해주세요.

<br>

## 관련 이슈

> closing할 이슈 번호를 작성해주세요.

- Close #이슈번호

<br>

2024-03-20 13:21 UTC, hongdayeong commented
> # Pull Request 요약
> PR에 대한 내용을 작성해주세요.
- zoom 아이콘 이미지 파일 svg로 변경
- 렌더링 하는 위치 변경 
- 디자인 시안대로 디자인 변경 및 추가
- 반응형 테블릿, 모바일 수정
> ## 작업 내용
> 작업 내용에 대해서 작성해주세요.
- zoom 아이콘 이미지 파일 png에서 svg로 변경
- 렌더링 하는 위치 변경 
- 디자인 시안대로 디자인 변경 및 추가
- 반응형 테블릿, 모바일 수정
> ## 참고 사항
> > 참고 사항이 있다면 첨부해주세요.
> 
> 
> ## 관련 이슈
> > closing할 이슈 번호를 작성해주세요.
> 
> * Close #이슈번호

2024-03-22 00:13 UTC, seongjin2427 requested changes
먹땡님~! 일단 보이는 코드 자체로 최대한 확인해봤습니닷 ㅎㅎ
한번 보시고 수정이 필요하실 것 같은 부분은 다 수정하시구 알려주세요~!

2024-03-22 00:13 UTC, seongjin2427 commented on src/pages/Home/SearchwordSection.tsx
> +  const visibleItemCount = 5;
상수와 같은 변수는 스네이크 케이스로 표현하는 것이 좋을 것 같아요!
다른 변수와는 출처나 활용용도가 다르니까요!
눈에 더 잘 띄게 해주는것이 좋을 것 같습니다!
ex) `VISIBLE_ITEM_COUNT`

2024-03-22 00:13 UTC, seongjin2427 commented on src/pages/Home/SearchwordSection.tsx
> +    if (startIndex <= 0) {
아무래도 `let`을 통한 변수 선언은 최대한 지양하는 것이 좋다보니까,
`const` 변수 선언으로 변경하는 것이 어떨까요?

ex)
```typescript
const calculatedStart = activeItem - Math.floor(visibleItemCount / 2);
// if (startIndex <= 0) {      
//  startIndex += totalItems;
// } // 현재 보여지는 아이템 목록 생성
const startIndex = calculatedStart <= 0 ? calculatedStart + totalItems : calculatedStart;
```

2024-03-22 00:13 UTC, seongjin2427 commented on src/pages/Home/SearchwordSection.tsx
> +      let itemNumber = ((startIndex + index - 1) % totalItems) + 1;
여기도 `let` 보다는 `const`로 변수를 선언하는 방향이 어떨까 싶습니다!
ex)
```typescript
const calculatedItemNumber = ((startIndex + index - 1) % totalItems) + 1;
// if (itemNumber === 0) {
//     itemNumber = totalItems;
// }
const itemNumber = calculatedItemNumber === 0 ? totalItems : calculatedItemNumber;
```

2024-03-22 00:13 UTC, seongjin2427 commented on src/pages/Home/SearchwordSection.tsx
> +              ? 'xl:text-[2rem] lg:text-[1.5rem] sm:text-[1.125rem] font-bold transform scale-125 shadow-lg rounded-full xl:w-[43.75rem] lg:w-[39.675rem] sm:w-[17.700rem] xl:h-[6rem] lg:h-[4.375rem]
`sm:w-[17.700rem]`은 `sm:w-[17.7rem]`으로 표현하면 좋을 것 같아요!

2024-03-22 00:13 UTC, seongjin2427 commented on src/pages/Home/SearchwordSection.tsx
> +  const renderItems = () => {
`renderItems`라는 커다란 렌더링 로직이 중간에 있으니까
`SearchwordSection`이라는 컴포넌트라는 전체 로직을 파악하는데 시간을 더 많이 소요하게 되는 것 같아요!
로직을 분리하는 등의 리팩토링이 추후에 추가적으로 필요할 것 같습니다. 😅

2024-03-22 04:33 UTC, hongdayeong commented on src/pages/Home/SearchwordSection.tsx
> +  const visibleItemCount = 5;
변경하였습니다!!

2024-03-22 04:35 UTC, hongdayeong commented on src/pages/Home/SearchwordSection.tsx
> +              ? 'xl:text-[2rem] lg:text-[1.5rem] sm:text-[1.125rem] font-bold transform scale-125 shadow-lg rounded-full xl:w-[43.75rem] lg:w-[39.675rem] sm:w-[17.700rem] xl:h-[6rem] lg:h-[4.375rem]
수정하면서 00이 잘 못 들어간 것 같아요ㅠㅠ수정하였습니다!!

2024-03-25 06:09 UTC, hongdayeong commented on src/pages/Home/SearchwordSection.tsx
> +      let itemNumber = ((startIndex + index - 1) % totalItems) + 1;
변경하였습니다!!

2024-03-25 06:09 UTC, hongdayeong commented on src/pages/Home/SearchwordSection.tsx
> +    if (startIndex <= 0) {
변경하였습니다!!

2024-03-26 07:30 UTC, hongdayeong commented on src/pages/Home/SearchwordSection.tsx
> +  const renderItems = () => {
renderItems 로직을 분리하였습니다!!

2024-03-26 07:44 UTC, seongjin2427 approved these changes
고생하셨습니다!! 👍

2024-03-26 08:12 UTC, merged