[feat] 메인페이지 교육일정 섹션 구현 진행중
yourteacher-org/yourteacher-fe pull request #39
Opened 2024-04-17 09:02 UTC by hongdayeong

# Pull Request 요약

> PR에 대한 내용을 작성해주세요.
메인페이지 교육일정 섹션 구현 진행중입니다
<br>

## 작업 내용

> 작업 내용에 대해서 작성해주세요.
메인페이지 교육일정 섹션 구현 진행중

<br>

## 참고 사항

> 참고 사항이 있다면 첨부해주세요.

<br>

## 관련 이슈

> closing할 이슈 번호를 작성해주세요.

- Close #이슈번호

<br>

2024-04-25 04:50 UTC, seongjin2427 commented
현재 기준으로 피드백 요청 해주셔서 수정이 필요할 것 같은 부분 정리해봅니다!

1. 반응형 UI 수정
- 공통
  - 배경 이미지가 다름
  - 로고 빠져있음
  - 신청일자, 교육일자와 아이콘의 간격이 다름

<br>

- 태블릿 (1024px 기준)
- 카드의 모서리 라운드 값을 줄여야 함
  - 피그마
    <img width="600" alt="image" src="https://github.com/yourteacher-org/yourteacher-fe/assets/59536977/1595b6b1-3428-48f8-9f88-73bbde7c3dd0">

  - 먹땡님 구현
    <img width="600" alt="image" src="https://github.com/yourteacher-org/yourteacher-fe/assets/59536977/6b4d07f0-e38d-484d-87a4-6166ec67a82c">

- 모바일 (390px 기준)
- 카드의 모서리 라운드 값을 줄여야 함
  - 피그마 
    <img width="300" alt="image" src="https://github.com/yourteacher-org/yourteacher-fe/assets/59536977/f449051b-a027-4cfe-b18d-1d5dd07f7e81">

  - 먹땡님 구현
    <img width="300" alt="image" src="https://github.com/yourteacher-org/yourteacher-fe/assets/59536977/b3cdc635-f031-43cd-a02e-5f9dfb9221ce">

2. 애니메이션 수정 필요
- 데스크탑에서 애니메이션이 종료된 후 살짝 어긋나는 모습이 보입니다.
- 태블릿과, 모바일에서는 카드 크기 변경에 따른 애니메이션 이동량에 대한 보정이 안 되어 있습니다.
    <img width="100%" alt="image" src="https://github.com/yourteacher-org/yourteacher-fe/assets/59536977/6c4499e3-1b00-4e98-b0a4-e8042a2b711d">
    <img width="600" alt="image" src="https://github.com/yourteacher-org/yourteacher-fe/assets/59536977/e31ef301-4a59-4d76-a112-e5a534648d7e">
    <img width="300" alt="image" src="https://github.com/yourteacher-org/yourteacher-fe/assets/59536977/a76edfd0-bb2b-43cb-ac7d-59423441c5a1">

2024-05-14 08:15 UTC, seongjin2427 requested changes
일부 요청사항을 제외하고는 좋은 것 같습니다!
다만 하나의 파일에 코드가 너무 길어서 파일로 코드 분리가 필요하다고 생각됩니다 하핳..

2024-05-14 08:15 UTC, seongjin2427 commented on src/pages/Home/SchedulSection.tsx
> +  PREV: `xl:-translate-x-[calc(50%-62.9rem)] lg:-translate-x-[calc(50%+39.7rem)] sm:-translate-x-[calc(50%+21.402rem)] transition-transform duration-${ANIMATION_DURATION} ease-in-out`,
1. PREV일때는 calc 내의 값을 -로 변경해주셔야 합니다!
안 그럼 좌/우측 모두 동일한 방향으로 움직입니다!
`+39.7rem` -> `-39.7rem`

2. 그리고 `rem` 단위는 최소 `0.0125rem` 단위로 +/- 해주시면 됩니당, (다른 단위로는 `0.25rem`, `0.375rem`, `0.5rem`, `0.75rem` 등)
   따라서 `xl:62.9rem -> 62.9125rem`, `lg:39.7rem -> 39.675rem`, `sm:21.402rem -> 21.375rem`

2024-05-14 08:15 UTC, seongjin2427 commented on src/pages/Home/SchedulSection.tsx
> +  NEXT: `xl:-translate-x-[calc(50%+62.9rem)] lg:-translate-x-[calc(50%+39.7rem)] sm:-translate-x-[calc(50%+21.402rem)] transition-transform duration-${ANIMATION_DURATION} ease-in-out`,
`duration-${ANIMATION_DURATION}`은 `duration-700`으로 수정 부탁드립니당
제가 작성하긴 했는데, 해당 문법으로는 duration이 적용이 안되는 것 같아요!

이후에 바로 위에 있을 상수인 `ANIMATION_DURATION` 값을 변경하게 되면
`duration-700` 값도 변경하는 것을 까먹으면 안 될 것 같습니다.

2024-05-21 08:52 UTC, hongdayeong commented on src/pages/Home/SchedulSection.tsx
> +  PREV: `xl:-translate-x-[calc(50%-62.9rem)] lg:-translate-x-[calc(50%+39.7rem)] sm:-translate-x-[calc(50%+21.402rem)] transition-transform duration-${ANIMATION_DURATION} ease-in-out`,
넵! 확인했습니다~

2024-08-27 07:14 UTC, seongjin2427 approved these changes
고생하셨습니다~

2024-10-19 16:33 UTC, merged