[feat] Header 컴포넌트 구현
yourteacher-org/yourteacher-fe pull request #9
Opened 2024-02-20 07:47 UTC by hongdayeong

# Pull Request 요약
PR에 대한 내용을 작성해주세요.
header 컴포넌트 구현
<br>

## 작업 내용
- header 컴포넌트 구현
- 라우터 구현
- header 스타일링

<br>

## 참고 사항

> 참고 사항이 있다면 첨부해주세요.
- 구현 사진
![image](https://github.com/yourteacher-org/yourteacher-fe/assets/127013736/1b5bbf1f-d415-44e3-90d9-1e9058aa9b8b)

<br>

## 관련 이슈

> closing할 이슈 번호를 작성해주세요.

- Close #6 
- Close #8 

<br>

2024-02-20 07:59 UTC, hongdayeong commented
> # Pull Request 요약
> PR에 대한 내용을 작성해주세요. header 컴포넌트 구현
> 
> ## 작업 내용
> * header 컴포넌트 구현
> * 라우터 구현
> * header 스타일링
> 
> 
> ## 참고 사항
> > 참고 사항이 있다면 첨부해주세요.
> 
> * 구현 사진
>   ![image](https://private-user-images.githubusercontent.com/127013736/306175522-1b5bbf1f-d415-44e3-90d9-1e9058aa9b8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MTYyMTksIm5iZiI6MTcwODQxNTkxOSwicGF0aCI6Ii8xMjcwMTM3MzYvMzA2MTc1NTIyLTFiNWJiZjFmLWQ0MTUtNDRlMy05MGQ5LTFlOTA1OGFhOWI4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQwNzU4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDA1OTM4OGZkYmYwODNlOWRmZGQ5MTE4OTM0MDY5YWRiZTk4MWU4N2IxZDYyYTJlM2RjYTQ2OTg1NGVkODRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TGqmIIJN9SS6-9DyLxqqk-jf8cX52UBqQpmKYhQDDww)
> 
> 
> ## 관련 이슈
> > closing할 이슈 번호를 작성해주세요.
> 
> * Close #3 
> * Close [라우터 구현 #8](https://github.com/yourteacher-org/yourteacher-fe/issues/8)

2024-02-23 05:07 UTC, seongjin2427 requested changes

2024-02-23 05:07 UTC, seongjin2427 commented on src/component/Data.tsx
> +// 이런 일반 객체의 경우에는 컴포넌트 밖으로 빼시는 것이 좋습니다.
이런 주석들은 다 지워주세욤~!

2024-02-23 05:07 UTC, seongjin2427 commented on src/component/Navbar.tsx
> +                  to={`/${MENU_PAGE[menu].toLowerCase().replace(/\s/g, '')}`}
`/${MENU_PAGE[menu]` 뒤의 `.toLowerCase().replace(/\s/g, '')`는 왜 있는건가요?
공백을 제거하기 위한 로직인 것 같은데 `MENU_PAGE[menu]`에는 공백이 들어간 데이터가 하나도 없어서요! ㅎㅎ

2024-02-23 05:07 UTC, seongjin2427 commented on src/component/Navbar.tsx
> +            <Link to="/signut-up" className="mr-3 text-14 group relative">
`/sign-up`이어야 할 것 같은데 `/signut-up으로 오타가 난 것 같습니다!
수정 부탁드려욤

2024-02-23 05:18 UTC, hongdayeong commented on src/component/Data.tsx
> +// 이런 일반 객체의 경우에는 컴포넌트 밖으로 빼시는 것이 좋습니다.
주석 정리 다했습니다!!

2024-02-23 05:19 UTC, hongdayeong commented on src/component/Navbar.tsx
> +                  to={`/${MENU_PAGE[menu].toLowerCase().replace(/\s/g, '')}`}
확인 후 공백 제거 코드는 제거하고 수정하였습니다!!

2024-02-23 05:19 UTC, hongdayeong commented on src/component/Navbar.tsx
> +            <Link to="/signut-up" className="mr-3 text-14 group relative">
오타 수정하였습니다!!

2024-02-23 05:19 UTC, seongjin2427 approved these changes

2024-02-23 05:47 UTC, merged